FROM php:8.4-fpm

ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION
ARG APP_ENV
ENV APP_ENV=$APP_ENV
ARG APP_SECRET
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG TASK_MESSENGER_TRANSPORT_DSN
ENV MESSENGER_TRANSPORT_DSN=$MESSENGER_TRANSPORT_DSN
ARG AWS_S3_KEY
ENV AWS_S3_KEY=$AWS_S3_KEY
ARG AWS_S3_SECRET
ENV AWS_S3_SECRET=$AWS_S3_SECRET
ARG AWS_S3_REGION
ENV AWS_S3_REGION=$AWS_S3_REGION
ARG URL_USER_MICROSERVICE
ENV URL_USER_MICROSERVICE=$URL_USER_MICROSERVICE
ARG URL_PLATFORM_MICROSERVICE
ENV URL_PLATFORM_MICROSERVICE=$URL_PLATFORM_MICROSERVICE



RUN apt-get update \
    && apt-get install -y \
        libicu-dev libzip-dev \
        libpq-dev \
        librabbitmq-dev \
        curl \
        libcurl4-openssl-dev \
        zip \
	    vim

RUN docker-php-ext-install intl \
        && docker-php-ext-install curl \
        && docker-php-ext-install zip \
        && docker-php-ext-install pdo_pgsql

RUN pecl install amqp && docker-php-ext-enable amqp opcache

RUN echo "alias ll='ls -ltha'" >> ~/.bashrc

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . .

COPY .docker/php/entrypoint_prod.sh /
ENTRYPOINT ["sh", "/entrypoint_prod.sh"]
